set(DL2HEADERFS ${CMAKE_CURRENT_SOURCE_DIR}/LDL2aArrayEvent.hh ${CMAKE_CURRENT_SOURCE_DIR}/LDL2aTelEvent.hh PARENT_SCOPE)
add_library(LASTDL2 SHARED  LRDL2aEvent.cpp)
target_include_directories(LASTDL2 PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}  ${ROOT_INCLUDE_DIRS})
target_link_libraries(LASTDL2 PUBLIC LASTDL1)


INSTALL(TARGETS LASTDL2 DESTINATION ${CMAKE_LIB_DIR})
